language: node_js
node_js: 
  - "16"
cache:
  directories:
    - node_modules

notifications:
  slack: 
    rooms: generositymarket:ZeAVzH5Ww7PB50ugNnwl5JuT#cs-ui-library-builds
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: "
      - "`%{commit_message}`"

stages:
  - Build and test
  - name: Npm Release
    if: branch = master
  - name: Deploy Storybook
    if: branch = master

jobs:
  include:
    - stage: Build and Test
      script: 
      - npm run build
      - npm test
    - stage: Npm Release
      node_js: "16"
      before_deploy: |
        PKG_VERSION=$(node -p "require('./package.json').version")
        NPM_TAG="latest"
        if [[ ${PKG_VERSION} =~ -next$ ]]; then
          NPM_TAG="next"
          SHORT_COMMIT_HASH=$(git rev-parse --short HEAD)
          UNIQ_PKG_VERSION="${PKG_VERSION}.${SHORT_COMMIT_HASH}"
          npm --no-git-tag-version version ${UNIQ_PKG_VERSION}
        fi
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        tag: "$NPM_TAG"
        # script: skip
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          branch: master
    - stage: Deploy Storybook
      before_deploy:
        - echo "Deploying Storybook to gh-pages ..."
        - npm run predeploy-storybook
      deploy:
        provider: pages # deploy to Github Pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: ./storybook-static # folder to be deployed
        repo: jgordy/stalls-ui
        target_branch: gh-pages
        on:
          branch: master