os: osx
language: node_js
node_js: 
  - "8"
cache:
  directories:
    - node_modules

notifications:
  slack: generositymarket:ZeAVzH5Ww7PB50ugNnwl5JuT

jobs:
  include:
    - stage: Build and test
      script: 
        - npm install
        - npm run build
        - npm test
    - stage: Npm Release
        script: 
          - echo "Deploying package changes to npm registry"
          - npm run build:publish
        deploy:
          provider: npm
          email: $NPM_EMAIL
          api_key: $NPM_TOKEN
          skip_cleanup: true
          on:
            tags: true
    - stage: Storybook release
        script: 
          - echo "Deploying Storybook changes to Github pages"
          - npm run build-storybook
        deploy:
          provider: pages # Tell Travis we want to deploy to Github Pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN # Will take the environment variable you created on step 5
          local_dir: storybook-static # The folder that needs to be deployed
          repo: jgordy/stalls-ui # Add your username/project_name here
          target_branch: gh-pages # Tell Travis to deploy on the gh-pages branch
          on:
            branch: master # Tell Travis to trigger a deploy only when we push to master
