os: osx
language: node_js
node_js: 
  - "8"
cache:
  directories:
    - node_modules

stages:
  - build and test
  - name: npm publish
    if: tags = true
  - name: deploy Storybook
    if: branch = master

notifications:
  slack: generositymarket:ZeAVzH5Ww7PB50ugNnwl5JuT

# build dist for npm publishing
before_deploy:
  - npm run build:publish
  - npm run build-storybook

jobs:
  include:
    - stage: build and test
      script: npm run build
      script: npm test
    - stage: npm release
      if: tag IS present
      node_js: "8"
      before_deploy:
        - npm run build:publish
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: Deploy Storybook
      deploy:
        before_deploy:
        - npm run build-storybook
        provider: pages # deploy to Github Pages
        skip-cleanup: false
        github-token: $GITHUB_TOKEN
        local_dir: storybook-static # folder to be deployed
        repo: jgordy/stalls-ui
        target_branch: gh-pages
        on:
          