os: osx
language: node_js
node_js: 
  - "8"
cache:
  directories:
    - node_modules

notifications:
  slack: 
    rooms: generositymarket:ZeAVzH5Ww7PB50ugNnwl5JuT#ui-library-builds
    on_success: always  # change: send a notification when the build status changes.
    on_failure: always  # always: always send a notification.
    template:
      - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
      - "Execution time: *%{duration}*"
      - "Message: %{commit_message}"

# build dist for npm publishing
# before_deploy:
#   - npm run build:publish
#   - npm run build-storybook

jobs:
  include:
    - stage: build and test
      script: 
      - npm run build
      - npm test
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: echo "Deploying to npm ..." # usually you do not want to rerun any tests
      deploy:
        before_deploy:
          - npm run build:publish
        provider: npm
        script: skip
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        on:
          tags: true
    - stage: Deploy Storybook
      if: branch = master
      script:
        - echo "Deploying Storybook ..."
        - npm run build-css
        - npm run build-storybook
      deploy:
        provider: pages # deploy to Github Pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: storybook-static # folder to be deployed
        repo: jgordy/stalls-ui
        target_branch: gh-pages
        on:
          